### ISSUE TITLE
native scrollbar shows when zooming out

### ISSUE THREAD

**Issue by alanontheweb** [albertogasparin/Optiscroll#20] opened 2016-06-18 17:00 UTC
Hi, this looks awesome. I'm always looking for a good implementation of custom scrollbars. I did a test with zooming out and unfortunately, the native scrollbar shows up behind the optiscroll. If I refresh the page (zoomed out), it works fine and hides the native scrollbar. Do you think this is something that can be recalculated/fixed on some sort of resize or zoom out event?

**Comment by albertogasparin** [comment] 2016-07-13 13:51
Well, quite tricky "bug" I suppose. Never thought about that behaviour before. As there is no reliable way to detect the zoom value, the only way I can think of handling the issue is by using units that are immutable, like `vw`, updated on resize.
So, given the scrollbar size in px, if divided by the window clientWidth you get the `vw` dimension. Then you update Optiscroll container styles, changing `right` and `bottom` values to be `vw`.
And this needs to be done after every resize, otherwise scrollbars will appear again.

**Comment by albertogasparin** [comment] 2017-03-31 12:24
Closing this as I don't see any actionable task.

**Closed by albertogasparin** 2017-03-31 12:24 UTC
